In [1]:
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns

In [2]:
env = pd.read_csv("../data/raw/env_air_.csv")

In [3]:
env.head()

,freq,unit,airpol,src_crf,geo\TIME_PERIOD,1990,1991,1992,1993,1994,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,A,MIO_T,CH4,CRF1,AT,0.05442,0.04970,0.04877,0.04635,0.03954,...,0.03087,0.03084,0.03199,0.02887,0.02811,0.02726,0.02873,0.02657,0.02694,0.02640
1,A,MIO_T,CH4,CRF1,BE,0.05939,0.05471,0.04767,0.04917,0.04371,...,0.03360,0.03342,0.03254,0.03197,0.03242,0.03087,0.03251,0.02870,0.02924,0.02843
2,A,MIO_T,CH4,CRF1,BG,0.09989,0.08456,0.09399,0.09496,0.08775,...,0.06470,0.06125,0.06590,0.06000,0.05644,0.05303,0.05795,0.06133,0.04673,0.03940
3,A,MIO_T,CH4,CRF1,CH,0.01529,0.01563,0.01496,0.01415,0.01324,...,0.00606,0.00601,0.00591,0.00542,0.00527,0.00495,0.00514,0.00455,0.00440,0.00430
4,A,MIO_T,CH4,CRF1,CY,0.00051,0.00052,0.00052,0.00052,0.00054,...,0.00065,0.00067,0.00074,0.00074,0.00077,0.00075,0.00076,0.00079,0.00072,0.00071

In [ ]:
env_long = env.copy()

env_long = env_long.melt(id_vars=["freq", "unit", "airpol", "src_crf", "geo\\TIME_PERIOD"], var_name="year")
env_long = env_long.drop(columns="freq")

env_long.head()

    unit airpol src_crf geo\TIME_PERIOD  year    value
0  MIO_T    CH4    CRF1              AT  1990  0.05442
1  MIO_T    CH4    CRF1              BE  1990  0.05939
2  MIO_T    CH4    CRF1              BG  1990  0.09989
3  MIO_T    CH4    CRF1              CH  1990  0.01529
4  MIO_T    CH4    CRF1              CY  1990  0.00051

In [27]:
env_gases = env_long[(env_long["unit"] == "MIO_T") & (env_long["src_crf"] == "TOTXMEMO")]

for i in ["airpol", "unit"]:
    print(env_gases[i].unique())

env_gases = env_gases[env_gases["year"]>="2004"]

env_gases

['CH4' 'CH4_CO2E' 'CO2' 'GHG' 'HFC_CO2E' 'HFC_PFC_NSP_CO2E' 'N2O'
 'N2O_CO2E' 'NF3_CO2E' 'PFC_CO2E' 'SF6_CO2E']
['MIO_T']

          unit    airpol   src_crf geo\TIME_PERIOD  year    value
746116   MIO_T       CH4  TOTXMEMO              AT  2004  0.33171
746117   MIO_T       CH4  TOTXMEMO              BE  2004  0.34821
746118   MIO_T       CH4  TOTXMEMO              BG  2004  0.30445
746119   MIO_T       CH4  TOTXMEMO              CH  2004  0.19371
746120   MIO_T       CH4  TOTXMEMO              CY  2004  0.03528
...        ...       ...       ...             ...   ...      ...
1829116  MIO_T  SF6_CO2E  TOTXMEMO              RO  2024  0.04527
1829117  MIO_T  SF6_CO2E  TOTXMEMO              SE  2024  0.04170
1829118  MIO_T  SF6_CO2E  TOTXMEMO              SI  2024  0.01230
1829119  MIO_T  SF6_CO2E  TOTXMEMO              SK  2024  0.00590
1829120  MIO_T  SF6_CO2E  TOTXMEMO              TR  2024  0.18443

[6237 rows x 6 columns]

In [32]:
teste = env_gases[(env_gases["geo\TIME_PERIOD"]=="PT") & (env_gases["year"]=="2020")]
teste[["airpol","value"]].sort_values(by="value", ascending=False)

           airpol     value
1607085       GHG  55.22422
1601863       CO2  39.39920
1598326  CH4_CO2E  10.23559
1615364  N2O_CO2E   3.67221
1607790  HFC_CO2E   1.90442
1594430       CH4   0.36556
1611804       N2O   0.01386
1617043  SF6_CO2E   0.01279

In [34]:
gases_dominantes = ["CO2", "CH4_CO2E", "N2O_CO2E"]
env_gases_final = env_gases[env_gases["airpol"].isin(gases_dominantes)]